"on":
 push:
  branches:
   - main

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
   - name: deploy binance
     uses: appleboy/ssh-action@master
     with:
      host: ${{secrets.SSH_KNOWN_HOSTs}}
      username: ${{secrets.USERNAME}}
      key: ${{secrets.SSH_PRIVATE_KEY}}
      script: |
       export NVM_DIR=~/.nvm
       source ~/.nvm/nvm.sh
       rm -rf test
       mkdir test
       cd test
       git clone git@github.com:spoli1986/binance
       echo 'Deployment to digital ocean finished'
