name: Deploy to Server

on:
 push:
  branches:
   - main

jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Set up SSH
     uses: webfactory/ssh-agent@v0.5.3
     with:
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

   - name: Deploy to server
     run: |
      rsync -avz --delete-after ./ spoli@binance-droplet:/var/www/spolarpeter.cc/html
     env:
      SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
